# -*- coding: utf-8 -*-
"""bs4-lab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/157b39fVT1waag1DpReuGmwnKdEp3FOfn
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install requests

import requests
from requests import get
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np

url = "https://nimhans.ac.in/academic-announcements/page/1/

results= requests.get(url)

print(results)

soup = BeautifulSoup(results.text, "html.parser")

announcements = soup.find_all('div', class_='wp-show-posts-inner')




list_of_ann = []

for container in announcements:
  ann = container.a.text
  list_of_ann.append(ann)

print(list_of_ann)

from time import sleep
from random import randint



pages = np.arange(1,10,1)

list_of_ann = []
list_of_url = []

for page in pages:
 
  page = requests.get('https://nimhans.ac.in/academic-announcements/page/'+str(page)+'/')
  print(page.url)
  soup = BeautifulSoup(results.text, "html.parser")
  announcements = soup.find_all('div', class_='wp-show-posts-inner')

  for container in announcements:
    ann = container.a.text
    print(ann)
    list_of_ann.append(ann)
  

  #sleep(randint(2,10))


nimhans_announcements = pd.DataFrame({
    'Announcement': list_of_ann
})

nimhans_announcements.to_csv('nimhans.csv')

